[project]
name = "ai-health-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mahak0505", email = "mahakb.556@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.3.18",
    "langchain-google-genai>=4.3.7",
    "python-dotenv>=1.2.3",
    "streamlit>=1.62.0",
]

 